// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniStore.DataAccess.Data;

#nullable disable

namespace MiniStore.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240209163345_feb9_1")]
    partial class feb9_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MiniStore.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Hero"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Villain"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Monster"
                        });
                });

            modelBuilder.Entity("MiniStore.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Tech City",
                            Name = "Tech Solution",
                            PhoneNumber = "6669990000",
                            PostalCode = "12121",
                            State = "IL",
                            StreetAddress = "123 Tech St"
                        },
                        new
                        {
                            Id = 2,
                            City = "Vid City",
                            Name = "Vivid Books",
                            PhoneNumber = "7779990000",
                            PostalCode = "66666",
                            State = "IL",
                            StreetAddress = "999 Vid St"
                        },
                        new
                        {
                            Id = 3,
                            City = "Lala land",
                            Name = "Readers Club",
                            PhoneNumber = "1113335555",
                            PostalCode = "99999",
                            State = "NY",
                            StreetAddress = "999 Main St"
                        });
                });

            modelBuilder.Entity("MiniStore.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("OrderHeaderId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderHeaderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("MiniStore.Models.OrderHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Carrier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OrderTotal")
                        .HasColumnType("float");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PaymentDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShippingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("OrderHeaders");
                });

            modelBuilder.Entity("MiniStore.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CatId")
                        .HasColumnType("int");

                    b.Property<string>("Char_Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Char_Race")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CatId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CatId = 1,
                            Char_Class = "Barbarian",
                            Char_Race = "Human",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incIdIdunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupIdatat non proIdent, sunt in culpa qui officia deserunt mollit anim Id est laborum.",
                            Image1 = "PSX_20231209_101355.jpg",
                            Image2 = "PSX_20231209_101425.jpg",
                            Image3 = "PSX_20231209_101454.jpg",
                            ListPrice = 0.0,
                            Name = "Faergus MacMurachadh (1)",
                            Price = 7.9900000000000002,
                            Price100 = 0.0,
                            Price50 = 0.0,
                            Size = 3
                        },
                        new
                        {
                            Id = 2,
                            CatId = 1,
                            Char_Class = "Monk",
                            Char_Race = "Dragonborn",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incIdIdunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupIdatat non proIdent, sunt in culpa qui officia deserunt mollit anim Id est laborum.",
                            Image1 = "Tsunami.png",
                            Image2 = "",
                            Image3 = "",
                            ListPrice = 0.0,
                            Name = "Black Tsunami",
                            Price = 7.9900000000000002,
                            Price100 = 0.0,
                            Price50 = 0.0,
                            Size = 3
                        },
                        new
                        {
                            Id = 3,
                            CatId = 1,
                            Char_Class = "Rogue",
                            Char_Race = "Halfling",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incIdIdunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupIdatat non proIdent, sunt in culpa qui officia deserunt mollit anim Id est laborum.",
                            Image1 = "PSX_20231209_100500(1).jpg",
                            Image2 = "PSX_20231209_100531.jpg",
                            Image3 = "PSX_20231209_100559.jpg",
                            ListPrice = 0.0,
                            Name = "Wendell PorrIdgepot",
                            Price = 6.9900000000000002,
                            Price100 = 0.0,
                            Price50 = 0.0,
                            Size = 2
                        },
                        new
                        {
                            Id = 4,
                            CatId = 1,
                            Char_Class = "Rogue",
                            Char_Race = "Elf",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incIdIdunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupIdatat non proIdent, sunt in culpa qui officia deserunt mollit anim Id est laborum.",
                            Image1 = "",
                            Image2 = "",
                            Image3 = "",
                            ListPrice = 0.0,
                            Name = "Alinar Merityn",
                            Price = 7.9900000000000002,
                            Price100 = 0.0,
                            Price50 = 0.0,
                            Size = 3
                        },
                        new
                        {
                            Id = 5,
                            CatId = 1,
                            Char_Class = "Barbarian",
                            Char_Race = "Minotaur",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incIdIdunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupIdatat non proIdent, sunt in culpa qui officia deserunt mollit anim Id est laborum.",
                            Image1 = "PSX_20231209_101655.jpg",
                            Image2 = "PSX_20231209_101723.jpg",
                            Image3 = "PSX_20231209_101804.jpg",
                            ListPrice = 0.0,
                            Name = "Norlak",
                            Price = 8.9900000000000002,
                            Price100 = 0.0,
                            Price50 = 0.0,
                            Size = 3
                        },
                        new
                        {
                            Id = 6,
                            CatId = 2,
                            Char_Class = "Thug",
                            Char_Race = "Bugbear",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incIdIdunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupIdatat non proIdent, sunt in culpa qui officia deserunt mollit anim Id est laborum.",
                            Image1 = "PSX_20231209_084029.jpg",
                            Image2 = "PSX_20231209_102538.jpg",
                            Image3 = "PSX_20231209_102505.jpg",
                            ListPrice = 0.0,
                            Name = "Big Bragg",
                            Price = 8.9900000000000002,
                            Price100 = 0.0,
                            Price50 = 0.0,
                            Size = 4
                        },
                        new
                        {
                            Id = 7,
                            CatId = 2,
                            Char_Class = "Thug",
                            Char_Race = "Bugbear",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incIdIdunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupIdatat non proIdent, sunt in culpa qui officia deserunt mollit anim Id est laborum.",
                            Image1 = "PSX_20231209_102308.jpg",
                            Image2 = "PSX_20231209_102350.jpg",
                            Image3 = "PSX_20231209_102431.jpg",
                            ListPrice = 0.0,
                            Name = "Big Brogg",
                            Price = 8.9900000000000002,
                            Price100 = 0.0,
                            Price50 = 0.0,
                            Size = 4
                        },
                        new
                        {
                            Id = 8,
                            CatId = 1,
                            Char_Class = "Cleric",
                            Char_Race = "Dwarf",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incIdIdunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupIdatat non proIdent, sunt in culpa qui officia deserunt mollit anim Id est laborum.",
                            Image1 = "PSX_20231209_102136.jpg",
                            Image2 = "PSX_20231209_102215.jpg",
                            Image3 = "",
                            ListPrice = 0.0,
                            Name = "Lomax Godhammer",
                            Price = 7.9900000000000002,
                            Price100 = 0.0,
                            Price50 = 0.0,
                            Size = 3
                        },
                        new
                        {
                            Id = 9,
                            CatId = 1,
                            Char_Class = "DruId",
                            Char_Race = "Tortle",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incIdIdunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupIdatat non proIdent, sunt in culpa qui officia deserunt mollit anim Id est laborum.",
                            Image1 = "PSX_20231209_101912.jpg",
                            Image2 = "PSX_20231209_101945.jpg",
                            Image3 = "PSX_20231209_102020.jpg",
                            ListPrice = 0.0,
                            Name = "Yehorta",
                            Price = 7.9900000000000002,
                            Price100 = 0.0,
                            Price50 = 0.0,
                            Size = 3
                        },
                        new
                        {
                            Id = 10,
                            CatId = 1,
                            Char_Class = "Cleric",
                            Char_Race = "Dwarf",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incIdIdunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupIdatat non proIdent, sunt in culpa qui officia deserunt mollit anim Id est laborum.",
                            Image1 = "PSX_20231209_101522.jpg",
                            Image2 = "PSX_20231209_101556.jpg",
                            Image3 = "PSX_20231209_101628.jpg",
                            ListPrice = 0.0,
                            Name = "Bulgrim Torvond",
                            Price = 7.9900000000000002,
                            Price100 = 0.0,
                            Price50 = 0.0,
                            Size = 3
                        },
                        new
                        {
                            Id = 11,
                            CatId = 1,
                            Char_Class = "Barbarian",
                            Char_Race = "Human",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incIdIdunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupIdatat non proIdent, sunt in culpa qui officia deserunt mollit anim Id est laborum.",
                            Image1 = "PSX_20231209_101142.jpg",
                            Image2 = "PSX_20231209_101233.jpg",
                            Image3 = "PSX_20231209_101312.jpg",
                            ListPrice = 0.0,
                            Name = "Faergus MacMurachadh (2)",
                            Price = 7.9900000000000002,
                            Price100 = 0.0,
                            Price50 = 0.0,
                            Size = 3
                        },
                        new
                        {
                            Id = 12,
                            CatId = 1,
                            Char_Class = "Fighter",
                            Char_Race = "Human",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incIdIdunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupIdatat non proIdent, sunt in culpa qui officia deserunt mollit anim Id est laborum.",
                            Image1 = "PSX_20231209_100917.jpg",
                            Image2 = "PSX_20231209_101010.jpg",
                            Image3 = "PSX_20231209_101048.jpg",
                            ListPrice = 0.0,
                            Name = "Bartel Radclif",
                            Price = 7.9900000000000002,
                            Price100 = 0.0,
                            Price50 = 0.0,
                            Size = 3
                        },
                        new
                        {
                            Id = 13,
                            CatId = 2,
                            Char_Class = "Warlock",
                            Char_Race = "Tiefling",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incIdIdunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupIdatat non proIdent, sunt in culpa qui officia deserunt mollit anim Id est laborum.",
                            Image1 = "PSX_20231209_100708.jpg",
                            Image2 = "PSX_20231209_100804.jpg",
                            Image3 = "PSX_20231209_100845.jpg",
                            ListPrice = 0.0,
                            Name = "Demeldor",
                            Price = 7.9900000000000002,
                            Price100 = 0.0,
                            Price50 = 0.0,
                            Size = 3
                        },
                        new
                        {
                            Id = 14,
                            CatId = 1,
                            Char_Class = "Cleric",
                            Char_Race = "Human",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incIdIdunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupIdatat non proIdent, sunt in culpa qui officia deserunt mollit anim Id est laborum.",
                            Image1 = "PSX_20231209_100256.jpg",
                            Image2 = "PSX_20231209_100340.jpg",
                            Image3 = "PSX_20231209_100405.jpg",
                            ListPrice = 0.0,
                            Name = "Cedric Greylock",
                            Price = 7.9900000000000002,
                            Price100 = 0.0,
                            Price50 = 0.0,
                            Size = 3
                        },
                        new
                        {
                            Id = 15,
                            CatId = 1,
                            Char_Class = "DruId",
                            Char_Race = "Human",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incIdIdunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupIdatat non proIdent, sunt in culpa qui officia deserunt mollit anim Id est laborum.",
                            Image1 = "PSX_20231209_100047.jpg",
                            Image2 = "PSX_20231209_100130.jpg",
                            Image3 = "PSX_20231209_100207.jpg",
                            ListPrice = 0.0,
                            Name = "Nulara Revenmar",
                            Price = 7.9900000000000002,
                            Price100 = 0.0,
                            Price50 = 0.0,
                            Size = 3
                        },
                        new
                        {
                            Id = 16,
                            CatId = 1,
                            Char_Class = "DruId",
                            Char_Race = "Human",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incIdIdunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupIdatat non proIdent, sunt in culpa qui officia deserunt mollit anim Id est laborum.",
                            Image1 = "PSX_20231209_095914.jpg",
                            Image2 = "PSX_20231209_095937.jpg",
                            Image3 = "PSX_20231209_100009.jpg",
                            ListPrice = 0.0,
                            Name = "Talmond Evonwood",
                            Price = 7.9900000000000002,
                            Price100 = 0.0,
                            Price50 = 0.0,
                            Size = 3
                        },
                        new
                        {
                            Id = 17,
                            CatId = 1,
                            Char_Class = "Paladin",
                            Char_Race = "Human",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incIdIdunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupIdatat non proIdent, sunt in culpa qui officia deserunt mollit anim Id est laborum.",
                            Image1 = "PSX_20231209_095721.jpg",
                            Image2 = "PSX_20231209_095801.jpg",
                            Image3 = "PSX_20231209_095836.jpg",
                            ListPrice = 0.0,
                            Name = "Dorian Ambrose",
                            Price = 7.9900000000000002,
                            Price100 = 0.0,
                            Price50 = 0.0,
                            Size = 3
                        },
                        new
                        {
                            Id = 18,
                            CatId = 2,
                            Char_Class = "Fighter",
                            Char_Race = "Drow",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incIdIdunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupIdatat non proIdent, sunt in culpa qui officia deserunt mollit anim Id est laborum.",
                            Image1 = "PSX_20231209_095512.jpg",
                            Image2 = "PSX_20231209_095606.jpg",
                            Image3 = "PSX_20231209_095650.jpg",
                            ListPrice = 0.0,
                            Name = "Calimar Tlin'orzza",
                            Price = 7.9900000000000002,
                            Price100 = 0.0,
                            Price50 = 0.0,
                            Size = 3
                        },
                        new
                        {
                            Id = 19,
                            CatId = 1,
                            Char_Class = "Wizard",
                            Char_Race = "Gnome",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incIdIdunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupIdatat non proIdent, sunt in culpa qui officia deserunt mollit anim Id est laborum.",
                            Image1 = "PSX_20231209_095308.jpg",
                            Image2 = "PSX_20231209_095354.jpg",
                            Image3 = "PSX_20231209_095430.jpg",
                            ListPrice = 0.0,
                            Name = "Elza Glitterbranch",
                            Price = 6.9900000000000002,
                            Price100 = 0.0,
                            Price50 = 0.0,
                            Size = 2
                        },
                        new
                        {
                            Id = 20,
                            CatId = 1,
                            Char_Class = "DruId",
                            Char_Race = "Human",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incIdIdunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupIdatat non proIdent, sunt in culpa qui officia deserunt mollit anim Id est laborum.",
                            Image1 = "PSX_20231209_095048.jpg",
                            Image2 = "PSX_20231209_095128.jpg",
                            Image3 = "PSX_20231209_095226.jpg",
                            ListPrice = 0.0,
                            Name = "Elias Leerstrom",
                            Price = 7.9900000000000002,
                            Price100 = 0.0,
                            Price50 = 0.0,
                            Size = 3
                        },
                        new
                        {
                            Id = 21,
                            CatId = 1,
                            Char_Class = "Wizard",
                            Char_Race = "Gnome",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incIdIdunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupIdatat non proIdent, sunt in culpa qui officia deserunt mollit anim Id est laborum.",
                            Image1 = "PSX_20231209_094812.jpg",
                            Image2 = "PSX_20231209_094919.jpg",
                            Image3 = "PSX_20231209_095009.jpg",
                            ListPrice = 0.0,
                            Name = "Fineela Nessik",
                            Price = 6.9900000000000002,
                            Price100 = 0.0,
                            Price50 = 0.0,
                            Size = 2
                        },
                        new
                        {
                            Id = 22,
                            CatId = 1,
                            Char_Class = "DruId",
                            Char_Race = "Halfling",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incIdIdunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupIdatat non proIdent, sunt in culpa qui officia deserunt mollit anim Id est laborum.",
                            Image1 = "PSX_20231209_094556.jpg",
                            Image2 = "PSX_20231209_094633.jpg",
                            Image3 = "PSX_20231209_094718.jpg",
                            ListPrice = 0.0,
                            Name = "Finnin Hierlihy",
                            Price = 6.9900000000000002,
                            Price100 = 0.0,
                            Price50 = 0.0,
                            Size = 2
                        },
                        new
                        {
                            Id = 23,
                            CatId = 2,
                            Char_Class = "Fighter",
                            Char_Race = "Human",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incIdIdunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupIdatat non proIdent, sunt in culpa qui officia deserunt mollit anim Id est laborum.",
                            Image1 = "PSX_20231209_094305.jpg",
                            Image2 = "PSX_20231209_094352.jpg",
                            Image3 = "PSX_20231209_094505.jpg",
                            ListPrice = 0.0,
                            Name = "Rutger Hightower",
                            Price = 8.9900000000000002,
                            Price100 = 0.0,
                            Price50 = 0.0,
                            Size = 3
                        },
                        new
                        {
                            Id = 24,
                            CatId = 1,
                            Char_Class = "Warlock",
                            Char_Race = "Tiefling",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incIdIdunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupIdatat non proIdent, sunt in culpa qui officia deserunt mollit anim Id est laborum.",
                            Image1 = "PSX_20231209_094024.jpg",
                            Image2 = "PSX_20231209_094110.jpg",
                            Image3 = "PSX_20231209_094201.jpg",
                            ListPrice = 0.0,
                            Name = "Valius Skamos",
                            Price = 7.9900000000000002,
                            Price100 = 0.0,
                            Price50 = 0.0,
                            Size = 3
                        },
                        new
                        {
                            Id = 25,
                            CatId = 1,
                            Char_Class = "Bard",
                            Char_Race = "Tiefling",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incIdIdunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupIdatat non proIdent, sunt in culpa qui officia deserunt mollit anim Id est laborum.",
                            Image1 = "PSX_20231209_090842.jpg",
                            Image2 = "PSX_20231209_090927.jpg",
                            Image3 = "PSX_20231209_091011.jpg",
                            ListPrice = 0.0,
                            Name = "ArchIdius Kazir",
                            Price = 7.9900000000000002,
                            Price100 = 0.0,
                            Price50 = 0.0,
                            Size = 3
                        },
                        new
                        {
                            Id = 26,
                            CatId = 2,
                            Char_Class = "Cleric",
                            Char_Race = "Drow",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incIdIdunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupIdatat non proIdent, sunt in culpa qui officia deserunt mollit anim Id est laborum.",
                            Image1 = "PSX_20231209_090603.jpg",
                            Image2 = "PSX_20231209_090643.jpg",
                            Image3 = "PSX_20231209_090727.jpg",
                            ListPrice = 0.0,
                            Name = "Chanzira Illyku'ur",
                            Price = 7.9900000000000002,
                            Price100 = 0.0,
                            Price50 = 0.0,
                            Size = 3
                        },
                        new
                        {
                            Id = 27,
                            CatId = 1,
                            Char_Class = "Bard",
                            Char_Race = "Gnome",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incIdIdunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupIdatat non proIdent, sunt in culpa qui officia deserunt mollit anim Id est laborum.",
                            Image1 = "PSX_20231209_090354.jpg",
                            Image2 = "PSX_20231209_090430.jpg",
                            Image3 = "PSX_20231209_090516.jpg",
                            ListPrice = 0.0,
                            Name = "Donella Tamble",
                            Price = 6.9900000000000002,
                            Price100 = 0.0,
                            Price50 = 0.0,
                            Size = 2
                        },
                        new
                        {
                            Id = 28,
                            CatId = 1,
                            Char_Class = "Fighter",
                            Char_Race = "Human",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incIdIdunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupIdatat non proIdent, sunt in culpa qui officia deserunt mollit anim Id est laborum.",
                            Image1 = "PSX_20231209_090137.jpg",
                            Image2 = "PSX_20231209_090221.jpg",
                            Image3 = "PSX_20231209_090306.jpg",
                            ListPrice = 0.0,
                            Name = "Allvar Mansc",
                            Price = 7.9900000000000002,
                            Price100 = 0.0,
                            Price50 = 0.0,
                            Size = 3
                        },
                        new
                        {
                            Id = 29,
                            CatId = 2,
                            Char_Class = "Sorcerer",
                            Char_Race = "Human",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incIdIdunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupIdatat non proIdent, sunt in culpa qui officia deserunt mollit anim Id est laborum.",
                            Image1 = "PSX_20231209_085828.jpg",
                            Image2 = "PSX_20231209_085857.jpg",
                            Image3 = "PSX_20231209_090008.jpg",
                            ListPrice = 0.0,
                            Name = "Carmen Hacari",
                            Price = 7.9900000000000002,
                            Price100 = 0.0,
                            Price50 = 0.0,
                            Size = 3
                        },
                        new
                        {
                            Id = 30,
                            CatId = 1,
                            Char_Class = "Bard",
                            Char_Race = "Tiefling",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incIdIdunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupIdatat non proIdent, sunt in culpa qui officia deserunt mollit anim Id est laborum.",
                            Image1 = "PSX_20231209_085630.jpg",
                            Image2 = "PSX_20231209_085700.jpg",
                            Image3 = "PSX_20231209_085742.jpg",
                            ListPrice = 0.0,
                            Name = "Kairon Daelius",
                            Price = 7.9900000000000002,
                            Price100 = 0.0,
                            Price50 = 0.0,
                            Size = 3
                        },
                        new
                        {
                            Id = 31,
                            CatId = 3,
                            Char_Class = "Aberration",
                            Char_Race = "Beholder",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incIdIdunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupIdatat non proIdent, sunt in culpa qui officia deserunt mollit anim Id est laborum.",
                            Image1 = "PSX_20231209_085439.jpg",
                            Image2 = "PSX_20231209_085513.jpg",
                            Image3 = "PSX_20231209_085543.jpg",
                            ListPrice = 0.0,
                            Name = "Bolla",
                            Price = 14.99,
                            Price100 = 0.0,
                            Price50 = 0.0,
                            Size = 4
                        },
                        new
                        {
                            Id = 32,
                            CatId = 3,
                            Char_Class = "Undead",
                            Char_Race = "Ogre Zombie",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incIdIdunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupIdatat non proIdent, sunt in culpa qui officia deserunt mollit anim Id est laborum.",
                            Image1 = "PSX_20231209_085246.jpg",
                            Image2 = "PSX_20231209_085258.jpg",
                            Image3 = "PSX_20231209_085331.jpg",
                            ListPrice = 0.0,
                            Name = "Grumbar",
                            Price = 14.99,
                            Price100 = 0.0,
                            Price50 = 0.0,
                            Size = 4
                        },
                        new
                        {
                            Id = 33,
                            CatId = 3,
                            Char_Class = "Monstrosity",
                            Char_Race = "Griffon",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incIdIdunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupIdatat non proIdent, sunt in culpa qui officia deserunt mollit anim Id est laborum.",
                            Image1 = "PSX_20231209_085009.jpg",
                            Image2 = "PSX_20231209_085045.jpg",
                            Image3 = "PSX_20231209_085154.jpg",
                            ListPrice = 0.0,
                            Name = "Torrenrak",
                            Price = 14.99,
                            Price100 = 0.0,
                            Price50 = 0.0,
                            Size = 4
                        },
                        new
                        {
                            Id = 34,
                            CatId = 3,
                            Char_Class = "Monstrosity",
                            Char_Race = "Manticore",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incIdIdunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupIdatat non proIdent, sunt in culpa qui officia deserunt mollit anim Id est laborum.",
                            Image1 = "PSX_20231209_084720.jpg",
                            Image2 = "PSX_20231209_084809.jpg",
                            Image3 = "PSX_20231209_084901.jpg",
                            ListPrice = 0.0,
                            Name = "Lauroumar",
                            Price = 14.99,
                            Price100 = 0.0,
                            Price50 = 0.0,
                            Size = 4
                        },
                        new
                        {
                            Id = 35,
                            CatId = 3,
                            Char_Class = "Giant",
                            Char_Race = "Troll",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incIdIdunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupIdatat non proIdent, sunt in culpa qui officia deserunt mollit anim Id est laborum.",
                            Image1 = "PSX_20231209_084457.jpg",
                            Image2 = "PSX_20231209_084546.jpg",
                            Image3 = "PSX_20231209_084634.jpg",
                            ListPrice = 0.0,
                            Name = "Oshryut",
                            Price = 12.99,
                            Price100 = 0.0,
                            Price50 = 0.0,
                            Size = 4
                        },
                        new
                        {
                            Id = 36,
                            CatId = 3,
                            Char_Class = "Fiend",
                            Char_Race = "Night Hag",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incIdIdunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupIdatat non proIdent, sunt in culpa qui officia deserunt mollit anim Id est laborum.",
                            Image1 = "PSX_20231209_084200.jpg",
                            Image2 = "PSX_20231209_084259.jpg",
                            Image3 = "PSX_20231209_084408.jpg",
                            ListPrice = 0.0,
                            Name = "Auntie Lucretia",
                            Price = 12.99,
                            Price100 = 0.0,
                            Price50 = 0.0,
                            Size = 4
                        });
                });

            modelBuilder.Entity("MiniStore.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("MiniStore.Models.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ProductId");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("MiniStore.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("CompanyId");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniStore.Models.OrderDetail", b =>
                {
                    b.HasOne("MiniStore.Models.OrderHeader", "OrderHeader")
                        .WithMany()
                        .HasForeignKey("OrderHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniStore.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderHeader");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MiniStore.Models.OrderHeader", b =>
                {
                    b.HasOne("MiniStore.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("MiniStore.Models.Product", b =>
                {
                    b.HasOne("MiniStore.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniStore.Models.ProductImage", b =>
                {
                    b.HasOne("MiniStore.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MiniStore.Models.ShoppingCart", b =>
                {
                    b.HasOne("MiniStore.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniStore.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MiniStore.Models.ApplicationUser", b =>
                {
                    b.HasOne("MiniStore.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("MiniStore.Models.Product", b =>
                {
                    b.Navigation("ProductImages");
                });
#pragma warning restore 612, 618
        }
    }
}
